version: "3.7"
services:
  app:
    build:
      args:
        user: mohamed
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: booking
    container_name: booking-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - booking
  db:
    image: mysql:8.0
    container_name: booking-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - booking
  nginx:
    image: nginx:alpine
    container_name: booking-nginx
    restart: unless-stopped
    ports:
      - 9090:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - booking
networks:
  booking:
    driver: bridge
